# ============================================================
# Paths to pretrained models (downloaded via download_models.py)
# ============================================================
MODEL_PATH=/data/ruijyang/pretrained_models/hunyuanwp/HunyuanVideo-1.5
WORLDPLAY_PATH=/data/ruijyang/pretrained_models/hunyuanwp/HY-WorldPlay

# Paths to negative prompt .pt files (generated by preprocess_vkitti_for_training.py)
export HUNYUAN_NEG_PROMPT_PATH=/data/ruijyang/datasets/vkitti_training_data_full/hunyuan_neg_prompt.pt
export HUNYUAN_NEG_BYT5_PROMPT_PATH=/data/ruijyang/datasets/vkitti_training_data_full/hunyuan_neg_byt5_prompt.pt

export WANDB_BASE_URL="https://api.wandb.ai"
export WANDB_MODE=online  # Change to "offline" if no internet, then sync later with: wandb sync
export TOKENIZERS_PARALLELISM=false
# export TRAINER_ATTENTION_BACKEND=TORCH_SDPA

# ============================================================
# GPU configuration
# ============================================================
NUM_GPUS=8
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

# Training arguments
# Batch size calculation: (num_gpus / sp_size) × gradient_accumulation × train_sp_batch_size
# With 8 GPUs, sp_size=4: (8/4) × 4 × 4 = 32
training_args=(
  --json_path /data/ruijyang/datasets/vkitti_training_data_full/train.json
  --causal
  --action
  --i2v_rate 0.2
  --train_time_shift 3.0
  --window_frames 24
  --wandb_key "${WANDB_API_KEY}"      # Set via: export WANDB_API_KEY=your_key or in .env file
  --wandb_entity "${WANDB_ENTITY}"  # Set in .env file
  --tracker_project_name "hunyuan-worldplay-vkitti"
  --output_dir /data/ruijyang/experiments/hunyuan_worldplay_vkitti
  --max_train_steps 10000
  --train_batch_size 4
  --train_sp_batch_size 4
  --gradient_accumulation_steps 4
  --num_latent_t 9
  --num_height 480
  --num_width 832
  --num_frames 77
  --enable_gradient_checkpointing_type "full"
  --seed 3208
  --weighting_scheme "logit_normal"
  --logit_mean 0.0
  --logit_std 1.0
)

# Parallel arguments
parallel_args=(
  --num_gpus $((NUM_GPUS * 1))
  --sp_size 4           # gpu number for each sp group, must divide window_frames evenly (24 % 4 == 0)
  --tp_size 1
  --hsdp_replicate_dim 1
  --hsdp_shard_dim $NUM_GPUS
)

# Model arguments
model_args=(
  --cls_name "HunyuanTransformer3DARActionModel"
  --load_from_dir ${MODEL_PATH}/transformer/480p_i2v
  --ar_action_load_from_dir ${WORLDPLAY_PATH}/ar_model/diffusion_pytorch_model.safetensors
  --model_path $MODEL_PATH
  --pretrained_model_name_or_path $MODEL_PATH
)

# Dataset arguments
# NOTE: On ROCm, num_workers > 0 can cause segfaults due to multiprocessing issues.
# Start with 0, increase to 1 or 2 if stable.
dataset_args=(
  --dataloader_num_workers 1
)

validation_args=(
#  --log_validation
  # --validation_dataset_file $VALIDATION_DATASET_FILE
  --validation_steps 500
  --validation_sampling_steps "50"
  --validation_guidance_scale "6.0"
)

# Optimizer arguments
optimizer_args=(
  --learning_rate 1e-5
  --mixed_precision "bf16"
  --checkpointing_steps 500
  --weight_decay 1e-4
  --max_grad_norm 1.0
)

# Miscellaneous arguments
miscellaneous_args=(
  --inference_mode False
  --checkpoints_total_limit 3
  --training_cfg_rate 0.1
  --multi_phased_distill_schedule "4000-1"
  --not_apply_cfg_solver
  --dit_precision "fp32"
  --num_euler_timesteps 50
  --ema_start_step 0
#  --enable_gradient_checkpointing_type "full"
)

export MASTER_PORT=29611

torchrun \
        --master_port=$MASTER_PORT \
        --nproc_per_node=$NUM_GPUS \
        --nnodes 1 \
        trainer/training/ar_hunyuan_w_mem_training_pipeline.py \
        "${parallel_args[@]}" \
        "${model_args[@]}" \
        "${dataset_args[@]}" \
        "${training_args[@]}" \
        "${optimizer_args[@]}" \
        "${validation_args[@]}" \
        "${miscellaneous_args[@]}"