# ============================================================
# Load environment variables (WandB credentials, etc.)
# ============================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "${SCRIPT_DIR}/../../../.env" ]; then
    source "${SCRIPT_DIR}/../../../.env"
fi

# ============================================================
# Paths to pretrained models (downloaded via download_models.py)
# ============================================================
MODEL_PATH=./pretrained_models/hunyuanwp/HunyuanVideo-1.5
WORLDPLAY_PATH=./pretrained_models/HY-WorldPlay

# MODEL_PATH=/wekafs/ryang/HY-WorldPlay/pretrained_models/HunyuanVideo-1.5
# AR_ACTION_MODEL_PATH=/wekafs/ryang/HY-WorldPlay/pretrained_models/HY-WorldPlay/ar_model/diffusion_pytorch_model.safetensors
# BI_ACTION_MODEL_PATH=/wekafs/ryang/HY-WorldPlay/pretrained_models/HY-WorldPlay/bidirectional_model/diffusion_pytorch_model.safetensors
# AR_DISTILL_ACTION_MODEL_PATH=/wekafs/ryang/HY-WorldPlay/pretrained_models/HY-WorldPlay/ar_distilled_action_model/diffusion_pytorch_model.safetensors
# ============================================================
# Dataset path (symlink in repo root -> vkitti_training_data_full)
# ============================================================
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
DATA_PATH=/data/ruijyang/datasets/vkitti_training_data_full #"${REPO_ROOT}/training_datasets_vkitti"

# Paths to negative prompt .pt files (generated by preprocess_vkitti_for_training.py)
export HUNYUAN_NEG_PROMPT_PATH=${DATA_PATH}/hunyuan_neg_prompt.pt
export HUNYUAN_NEG_BYT5_PROMPT_PATH=${DATA_PATH}/hunyuan_neg_byt5_prompt.pt

# Rewrite paths in train.json to use DATA_PATH (handles data copied/moved to new location)
python3 -c "
import json
import os
data_path = os.path.abspath('${DATA_PATH}')
train_json = os.path.join(data_path, 'train.json')
if os.path.exists(train_json):
    with open(train_json) as f:
        data = json.load(f)
    if data:
        old_base = data[0]['latent_path'].rsplit('/latents/', 1)[0]
        if old_base != data_path:
            for item in data:
                for key in ('latent_path', 'pose_path', 'action_path'):
                    if key in item and item[key]:
                        item[key] = item[key].replace(old_base, data_path)
            with open(train_json, 'w') as f:
                json.dump(data, f, indent=2)
            print(f'Updated train.json paths: {old_base} -> {data_path}')
"

export WANDB_BASE_URL="https://api.wandb.ai"
export WANDB_MODE=online
export TOKENIZERS_PARALLELISM=false
# Force unbuffered Python output for real-time logging
export PYTHONUNBUFFERED=1
# Use TORCH_SDPA since flash_attn is not installed on ROCm
# export TRAINER_ATTENTION_BACKEND=TORCH_SDPA

# Enable AITER (AMD CK/ASM optimized flash attention + RMSNorm kernels)
# Requires: pip install aiter (or bash install_FA_Aiter_rocm.sh)
export USE_AITER=1

# Enable torch.compile to fuse small ops (norms, activations, element-wise)
# First step is slow (compilation), subsequent steps are faster
export TORCH_COMPILE=1
export TORCH_COMPILE_MODE="max-autotune"   # or reduce-overhead, max-autotune
# ============================================================
# GPU configuration
# ============================================================
NUM_GPUS=8
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

# Training arguments
training_args=(
  --mode finetuning
  --json_path ${DATA_PATH}/train.json
  --causal
  --action
  --i2v_rate 0.2
  --train_time_shift 3.0
  --window_frames 32
  --wandb_key "${WANDB_API_KEY}"
  --wandb_entity "${WANDB_ENTITY}"
  --tracker_project_name "hy-worldplay-vkitti"
  --output_dir /data/ruijyang/training_output/run4_full_run
  --max_train_steps 500
  --train_batch_size 1
  --train_sp_batch_size 1
  --gradient_accumulation_steps 1
  --num_latent_t 9
  --num_height 480
  --num_width 832
  --num_frames 77
  --enable_gradient_checkpointing_type "full"
  --seed 3208
  --weighting_scheme "logit_normal"
  --logit_mean 0.0
  --logit_std 1.0
)

# Parallel arguments
parallel_args=(
  --num_gpus $((NUM_GPUS * 1))
  --sp_size 2           # gpu number for each sp group, must divide window_frames evenly (32 % 2 == 0)
  --tp_size 1
  --hsdp_replicate_dim 1
  --hsdp_shard_dim $NUM_GPUS
)

# Model arguments
# load_from_dir: AR model directory (has config.json with AR-specific architecture)
# ar_action_load_from_dir: full model weights including action params
# NOTE: Using ar_model (non-distilled, 50-step) instead of ar_distilled_action_model (4-step)
#       for better training gradients. The distilled model is optimized for fast inference,
#       not for training. Both have the same action parameters, but ar_model has weights
#       trained with full diffusion steps.
model_args=(
  --cls_name "HunyuanTransformer3DARActionModel"
  --load_from_dir ${WORLDPLAY_PATH}/ar_model
  --ar_action_load_from_dir ${WORLDPLAY_PATH}/ar_model/diffusion_pytorch_model.safetensors
  --model_path $MODEL_PATH
  --pretrained_model_name_or_path $MODEL_PATH
)

# Dataset arguments
dataset_args=(
  --data-path ${DATA_PATH}
  --dataloader_num_workers 4
)

validation_args=(
#  --log_validation
  # --validation_dataset_file $VALIDATION_DATASET_FILE
  --validation_steps 250
  --validation_sampling_steps "50"s
  --validation_guidance_scale "6.0"
)

# Optimizer arguments
# Higher LR (5e-5) for faster learning on small dataset (100 samples).
# Cosine schedule with min_lr_ratio=0.1 decays to 5e-6 over 500 steps.
optimizer_args=(
  --learning_rate 5e-5
  --lr_scheduler "cosine_with_min_lr"
  --lr_warmup_steps 20
  --min_lr_ratio 0.1
  --mixed_precision "bf16"
  --checkpointing_steps 100
  --weight_decay 1e-4
  --max_grad_norm 0.5
)

# Miscellaneous arguments
miscellaneous_args=(
  --inference_mode False
  --checkpoints_total_limit 3
  --training_cfg_rate 0.1
  --multi_phased_distill_schedule "4000-1"
  --not_apply_cfg_solver
  --dit_precision "fp32"
  --num_euler_timesteps 50
  --ema_start_step 100
  --use_ema
)

export MASTER_PORT=29611

torchrun \
        --master_port=$MASTER_PORT \
        --nproc_per_node=$NUM_GPUS \
        --nnodes 1 \
        trainer/training/ar_hunyuan_w_mem_training_pipeline.py \
        "${parallel_args[@]}" \
        "${model_args[@]}" \
        "${dataset_args[@]}" \
        "${training_args[@]}" \
        "${optimizer_args[@]}" \
        "${validation_args[@]}" \
        "${miscellaneous_args[@]}"

